version: '3'
services:
  base:
    build: .
  flask_api:
    build:
      context: .
      dockerfile: flask_api/Dockerfile
    ports:
    - "9090:9090"
    volumes:
    - .:/srv
    depends_on:
      - base
  face_descriptor:
    build:
      context: .
      dockerfile: face_description/Dockerfile
    volumes:
    - .:/srv
    depends_on:
      - base
  db_api:
    build:
      context: .
      dockerfile: db/Dockerfile
    ports:
    - "8181:8181"
    volumes:
    - .:/srv
    depends_on:
      - base